export { default as NotFound } from "./NotFound";
export { default as Error } from "./Error";
export { default as Landing } from "./Landing";
export { default as Home } from "./Home";
export { default as Post } from "./Post";
export { default as Explore } from "./Explore";
export { default as Profile } from "./Profile";
export { default as ProfilePost } from "./ProfilePost";
export { default as ProfileLikedPost } from "./ProfileLikedPost";
export { default as ProfileSavedPost } from "./ProfileSavedPost";
export { default as Setting } from "./Setting";
export { default as Login} from "./Login";
export { default as Signup } from "./Signup";
